# This workflow will build a .NET project and perform a Sonar scan with code coverage using Coverlet

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console
    - name: Install sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Begin Sonar scan
      run: dotnet sonarscanner begin /k:"hkeasv_BusCompany_DataDrivenTesting" /o:"hkeasv" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token=${{ secrets.SONAR_TOKEN }}
    - name: Collect code coverage using Coverlet
      run: coverlet /Buscompany.UnitTests/bin/Debug/net10.0/Buscompany.UnitTests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
    - name: End Sonar scan
      run: dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}
